### ISSUE TITLE
React Native Library for TV

### ISSUE THREAD

**Issue by YBDevelopment** [react-native-community/react-native-tvos#8] opened 2019-09-04 10:31 UTC
I want to create a Native Module in React Native for TV. 
The process works fine for iPhone but NOT for TV
for iOS : no tv target was created so I  adjust it in Xcode to tv platform 
After Embedding the library in RN project and access native module function  I get errors  "Cannot read property 'functionalists' of undefined"
React Native version:0.59.8 (for tv only this version works)
## Steps To Reproduce

Reference : https://medium.com/wix-engineering/creating-a-native-module-in-react-native-93bab0123e46

Waiting for your answer ASAP 
Thanks!

**Comment by dlowder-salesforce** [comment] 2019-09-04 15:18
`react-native-create-library` hasn’t been updated in two years, and seems to be from a personal repo, not a Facebook or a RN community repo.  I can have a look to see if there is a newer and better supported solution.

**Comment by YBDevelopment** [comment] 2019-09-05 06:23
Thanks. Please update me if you find solution

**Comment by YBDevelopment** [comment] 2019-09-08 11:20
Hi 
I try to create the module by $ create-react-native-module
like is written FB documantaion  : https://facebook.github.io/react-native/docs/native-modules-setup

Nothing changed the library does not work on tv 
The project with the library is compiled but on runtime when I call native function that exported by RNBridge I get the error : 
**Unhandled JS Exception: Cannot read property 'Func' of undefined**

Any idea????

Thanks!

**Comment by dlowder-salesforce** [comment] 2019-09-08 16:24
I think the problem is that the podspec for the module created by `create-react-native-module` does not include tvOS support.

This is the change needed:

```diff
diff -u react-native-tv-test-module.podspec.orig react-native-tv-test-module.podspec
--- react-native-tv-test-module.podspec.orig	2019-09-08 09:20:56.000000000 -0700
+++ react-native-tv-test-module.podspec	2019-09-08 09:21:36.000000000 -0700
@@ -13,7 +13,7 @@
   s.license      = "MIT"
   # s.license    = { :type => "MIT", :file => "FILE_LICENSE" }
   s.authors      = { "Your Name" => "yourname@email.com" }
-  s.platform     = :ios, "7.0"
+  s.platforms    = { :ios => "7.0", :tvos => "12.0" }
   s.source       = { :git => "https://github.com/github_account/react-native-tv-test-module.git", :tag => "#{s.version}" }
 
   s.source_files = "ios/**/*.{h,m,swift}"
```

I'll give this a shot, and if this works, I'll file a PR with create-react-native-module repo to get this fixed.  Please feel free to test this yourself.

**Comment by dlowder-salesforce** [comment] 2019-09-08 23:45
@YBDevelopment : see PR for `create-react-native-module`above that was merged today. It does indeed fix the issue.

**Closed by dlowder-salesforce** 2019-09-08 23:45 UTC
