### ISSUE TITLE
react-native-tvos releases do not have "android" directory, breaking Android builds

### ISSUE THREAD

**Issue by sjpeter** [react-native-community/react-native-tvos#7] opened 2019-08-28 02:12 UTC
I run: 
react-native init TeatTv --version=react-native@npm:react-native-tvos@0.60.4-2
then:
react-native run-android

## Task  :app:compileDebugJavaWithJavac

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings
13 actionable tasks: 13 executed
D:\Program\native\TeatTv\android\app\src\main\java\com\teattv\MainApplication.java:7: ����: �����com.facebook.hermes.reactexecutor������
import com.facebook.hermes.reactexecutor.HermesExecutorFactory;
                                        ^
D:\Program\native\TeatTv\android\app\src\main\java\com\teattv\MainApplication.java:8: ����: �Ҳ�������
import com.facebook.react.bridge.JavaScriptExecutorFactory;
                                ^
  ����:   �� JavaScriptExecutorFactory
  λ��: ����� com.facebook.react.bridge
D:\Program\native\TeatTv\android\app\src\main\java\com\teattv\MainApplication.java:9: ����: �Ҳ�������
import com.facebook.react.ReactApplication;

## this package.js
  "dependencies": {
    "react": "16.8.6",
    "react-native": "npm:react-native-tvos@0.60.4-2"
  },

**Comment by sjpeter** [comment] 2019-08-28 02:16
help

**Comment by sjpeter** [comment] 2019-08-28 05:44
Thinks,you know about android TV development.
I need development android TV App.

**Comment by dlowder-salesforce** [comment] 2019-09-05 07:40
This is not an Apple TV issue, and should be submitted to the core repo instead.

**Comment by hufkens** [comment] 2019-09-13 08:14
@NickAVolpe We currently have an app running on tvOS and Android TV and face the same challenges of supporting both platforms. Until now we were on react-native 0.59.8, but we are upgrading to this version. I'm hoping to start contributing back.

@dlowder-salesforce Is it ok for you that we also add Android TV related features and patches in this repo so it becomes the TV version?

**Comment by dlowder-salesforce** [comment] 2019-09-13 17:58
@hufkens YES YES I welcome some Android TV help 👍 

@NickAVolpe the compile error may be a version mismatch between version numbers in the Android files and the version number in package.json.  I'll have a look to see.

**Comment by dlowder-salesforce** [comment] 2019-09-13 18:40
Ok I found the root cause for this issue -- the `android` directory is missing from `node_modules/react-native` if this repo is used instead of core 0.60.4.  Bizarre.  Investigating to see why.

**Comment by dlowder-salesforce** [comment] 2019-09-13 19:01
Android directory is missing because there is a script I have to run before publishing to NPM.  Will fix this in an upcoming release.

Workaround: 
- Generate a new project using core `react-native@0.60.4`
- Copy `node_modules/react-native/android` from that project into `node_modules/react-native` in a project generated with this repo

Then `react-native run-android` should work as expected.

**Comment by brodybits** [comment] 2019-09-13 21:00
Looking forward to the bug fix. Here is a possibly quicker workaround that worked for me:

* create a new blank project with `react-native` as a dependency:
  - `mkdir temp-project && cd temp-project`
  - `yarn init -y`
  - `cat package.json` # (optional but recommended)
  - `yarn add react-native@latest`
* do the second workaround step above:
  - copy `node_modules/react-native/android` from that project into `node_modules/react-native` in a project generated with this repo

I think this issue came up because this project is a fork of react-native (#11).

**Comment by dlowder-salesforce** [comment] 2019-09-13 22:06
@brodybits is correct, this issue is because we are a fork of the core repo.

Correct solution:  in the top level directory, run `./gradlew ReactAndroid:installArchives` before publishing to NPM.

That currently fails for me in the Javadoc generation, because of an issue with javax.annotation having been removed from OpenJDK 11.  Working on a solution for this.

**Comment by dlowder-salesforce** [comment] 2019-09-14 01:11
The installArchives error I'm seeing is being tracked at https://github.com/facebook/react-native/issues/25625

**Comment by dlowder-salesforce** [comment] 2019-09-14 01:54
@hufkens @NickAVolpe : to unblock this issue temporarily while we wait for a proper solution, I can comment out line 102 of `ReactAndroid/release.gradle`, so that the sources jar is generated, but the Javadoc jar is not.  Would you be ok with that for now?

**Comment by brodybits** [comment] 2019-09-15 15:05
> to unblock this issue temporarily while we wait for a proper solution, I can comment out line 102 of `ReactAndroid/release.gradle`

I would sure favor that kind of a solution. I think the purpose of this package should be to get tvOS working with the other supported platforms (iOS and Android), not to generate any Javadoc. (It sound like the Javadoc JAR would not be needed to run on Android.) Thanks!

**Comment by dlowder-salesforce** [comment] 2019-09-15 18:03
Fixed in https://github.com/react-native-community/react-native-tvos/releases/tag/v0.60.4-6 .

**Closed by dlowder-salesforce** 2019-09-15 18:03 UTC
