### ISSUE TITLE
TextInput on focus ignores placeholderTextColor

### ISSUE THREAD

**Issue by ArturasMi** [react-native-community/react-native-tvos#31] opened 2019-12-02 10:49 UTC
Hi, first of all thanks for maintaining react-native-tvos I really love it! However I came across a strange issue with TextInputs. I made some primitive styling and once I tried to move around the screen I noticed that after focusing on TextInput it sets placeholder color back to black. I'm not sure if that's a bug or I just don't know how to use it.

IDEs:
Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
npmPackages:
react: 16.9.0 => 16.9.0
react-native-tvos: 0.61.2-0
npmGlobalPackages:
react-native-cli: 2.0.1
react-native-git-upgrade: 0.2.7

## Steps To Reproduce

<TextInput
          placeholder="Some text"
          placeholderTextColor="red"
          style={style.AwesomeStyle}
          onChangeText={ do stuff... }
        />

  AwesomeStyle: {
    paddingVertical: 15,
    fontSize: 14,
  },

**Comment by dlowder-salesforce** [comment] 2020-01-20 21:42
Is this the same issue as #22 ?

**Comment by dlowder-salesforce** [comment] 2020-01-27 02:08
Closing as a dupe of #22

**Closed by dlowder-salesforce** 2020-01-27 02:08 UTC

**Comment by henninghall** [comment] 2021-07-12 13:16
It doesn't seem to be the exact same issue as #22

I am able to reproduce it by setting `placeholderTextColor`, focusing text input and then blurring text input. 

```
import { TextInput } from 'react-native';

... 

   <TextInput
        value={''}
        placeholder={'Search'}
        style={{ width: 400, height: 80, fontSize: 20 }}
        placeholderTextColor="white"
      />
```
