### ISSUE TITLE
TouchableOpacity elements in previous screens in navigation stack are still accessible in next screen

### ISSUE THREAD

**Issue by oscadev** [react-native-community/react-native-tvos#43] opened 2020-01-28 21:19 UTC
I have a simple navigation stack with 3 screens. To simplify, lets say screen 1 has 3 buttons named button1, button2, etc. Screen 2 has 3 buttons as well. Now, when I go to the second screen, if I am highlighting the first button and I go left, it will go and highlight button3 from screen1 off-screen. I have confirmed this by adding a console.log to each button on every page to identify itself ("button3 on screen one is highlighted" etc). 

Is the solution to replace all the buttons with an empty array in screen 1 when I go to screen 2, or is there a more correct way?

**Comment by dlowder-salesforce** [comment] 2020-01-29 01:25
Could you post your JS code so I can try it out and see the issue?

**Comment by NickAVolpe** [comment] 2020-01-29 02:07
We had this same problem with react-navigation. Our solution was similar to the one you suggested  @oscadev. When we navigate to a new screen, we render an empty View component for the screen underneath in the stack.

**Comment by oscadev** [comment] 2020-01-29 20:06
@dlowder-salesforce Thanks for the reply. I was about to make my project public so that you can see, but then I saw Nick's answer. I went ahead and added navigation listeners for "didFocus" on each screen so that I can re-render the content when going back, and render nothing when leaving the screen. This worked. Thanks @NickAVolpe  . @dlowder-salesforce If you are still interested in looking for future cases, I can add you as a collaborator if you wish. Thanks! (will leave issue open in case DL wants to take a look and fix the issue so that it works without the workaround described).

**Comment by dlowder-salesforce** [comment] 2020-01-29 20:09
Yes thanks @oscadev please add me -- it would be good to have additional testing for react-navigation on tvOS, and maybe add pointers to the README here.  I will also take a look and see if there is an underlying issue in the native code.

**Comment by oscadev** [comment] 2020-01-29 20:23
@dlowder-salesforce I sent you the invite! There is nothing in the readme as I am the only one working on this project, but I can add details here! Basically, I have the app.js which includes the very simple stack navigator with the 3 screens. Each screen is located in the "screens" folder. 

I have a list of toucahableopacity items in screen one in a horizontal row. Once selecting one of these items, it goes to screen 2 which then has another list of sub-items to the first item chosen. When screen 2 loads, if you were to press left on the keyboard, it would highlight an item from screen 1. All the items on each screen will console log themselves so that you can see in terminal what is focused. The third screen is a video player that plays the item chosen in screen 2. This likewise had the issue of highlighting things from screen 2.

The issue is fixed because I implemented the workaround of rendering a screen with no toucahable elements when I leave the screen, and then re-rendering the elements again when returning to the screen (using navigation addlistener didfocus ).  Would you like me to make a branch ("broken") where I have removed the fixes, or is that not necessary? Let me know!

**Comment by oscadev** [comment] 2020-01-29 20:26
@dlowder-salesforce I havent pushed the fixed version, so the current version on master actually has the issues discussed!

**Comment by dlowder-salesforce** [comment] 2020-01-29 20:40
Yep I see the issue.... weird that the left nav goes back to the home screen and always to the second from the left tile, not the left most tile.  Something strange is definitely going on.

**Comment by oscadev** [comment] 2020-01-29 21:12
@dlowder-salesforce sorry, now that mentioned that behavior, I had added a “navigate to homepage” function when either the first or second element in the first page became focused. To avoid that, choose an element further in on both pages (for example the 10th element on page 1 and then the 5th on page 2) and then press left when already on the furthest left element. In this case, it will not load home screen again, but you will see focus leave and terminal will show elements in Home screen are being highlighted

**Comment by oscadev** [comment] 2020-01-29 21:21
@dlowder-salesforce to simplify your troubleshooting, I made a branch called "broken" where I removed all the fixes, and also removed that function that reloaded home screen when pressing left on the first item in screen 2 (that was another workaround I was trying out before).

**Comment by colin-oos** [comment] 2020-03-07 00:06
We are having the same issue. We have it with stack navigators like you @oscadev and found it is also an issue with material tab navigators as well. If the next tab has touchable elements, it will let me continue to focus onto the next tab from my active tab. 

I did the same workaround you mentioned but run into a significant performance issue when switching tabs or going back in a stack as the app has to re-render all the imagery I am using in my touchable elements. I think I could cache the imagery and that would help, but that solution still seems pretty hacky to me. I noticed that `RCTVView` has a property called `isTVSelectable` but this property isn't exposed on touchable elements in react-native. If I'm understanding everything right (I'm only 1 year new with react-native), couldn't a property called `isTVSelectable` be added to touchable elements so when the screen they are on isn't active we can set it to `false`? I am exploring that solution myself now, but figured I'd post about it here incase I am on a wrong path.

**Comment by oscadev** [comment] 2020-03-07 00:36
@colin-oos Yes, I was going to recommend either caching/hiding without re-rendering. Just add a conditional to render the items or render null depending on a boolean like "showElements" that turns to "off" when you click to leave the page.

**Comment by colin-oos** [comment] 2020-03-07 00:56
> @colin-oos Yes, I was going to recommend either caching/hiding without re-rendering. Just add a conditional to render the items or render null depending on a boolean like "showElements" that turns to "off" when you click to leave the page.

Yeah, thats essentially what I'm doing now only without caching the images. The issue is, conditionally rendering either `null` or the touchable element will affectively re-render the touchable element and all of its children

**Comment by oscadev** [comment] 2020-03-07 01:48
@colin-oos if it is only re-rendering (without having to refetch data or do other tasks that take a long time) it should re-render instantaneously, I think.

**Comment by colin-oos** [comment] 2020-03-07 02:19
@oscadev In my case I do need to refetch data. My app is loading the uri's of the imagery on child components. There is also potential that my app may require other API related tasks in the children of my touchable components. I believe I found a fix to the problem though, and this might be a more elegant solution for yourself too. 

I opened up the property `isTVSelectable` on `TouchableHighlight` and `TouchableOpacity`. This way, instead of rendering `null` or another `View` when  the screen isn't active, you can set on the touchable components `isTVSelectable` to false. This disables the ability to focus on the views without re-rendering the view and its children. In fact, this property I feel like can be useful in many other ways than just react-navigation. I could see the potential case for wanted to grey out or disable touchable components in a TV app. So I may also make a PR to see what @dlowder-salesforce thinks.

For now, you can find my changes on the forked branch [colin-oos/react-native-tvos#tvos-v0.61.5](https://github.com/colin-oos/react-native-tvos/tree/tvos-v0.61.5) I made if you want to give it a try and see if it works well for you.

**Comment by dlowder-salesforce** [comment] 2020-03-12 16:47
@colin-oos thank you VERY much, I will take a look at your branch.

**Comment by dlowder-salesforce** [comment] 2020-03-25 00:48
@colin-oos I have some cycles to work on this now... would you be able to share your test project where you are using the new `isTVSelectable` property on Touchables to fix the issue?

**Comment by dlowder-salesforce** [comment] 2020-04-04 00:06
@colin-oos @oscadev I was able to put together a new project using the latest `react-navigation` that reproduces the issue.  See https://github.com/dlowder-salesforce/ReactNavigationTVDemo.  It uses a forked `react-native-screens` that fixes its tvOS compilation issues.  Now I will be able to try different approaches to fix the issue.

**Comment by dlowder-salesforce** [comment] 2020-04-05 06:35
I do see that using `isTVSelectable` does fix the issue and doesn't require rerender.  However, in the simulator, I am seeing a weird behavior where when navigating back, it takes a long time (about 1 second) for the left most button in a screen to pick up the change to `isTVSelectable` and get the default focus that it should have.  Investigating.

**Comment by keshavkaul** [comment] 2020-04-06 08:30
Solution for me was initially to replace TouchableOpacity with normal View when screen is blurred and switch back when screen is focused. But due to this there were performance issues and focus issues. Then I sought to subclass RCTTVView to create a custom Selectable Button Element, exposing the isTVSelectable property and handles focus, onPress events

**Comment by dlowder-salesforce** [comment] 2020-04-06 18:11
@keshavkaul @colin-oos I have invited you to the repo; once you accept, please review PR #62 .

**Comment by dlowder-salesforce** [comment] 2020-04-09 01:58
#62 is merged, and appears in https://github.com/react-native-community/react-native-tvos/releases/tag/v0.61.5-1 .  Closing.

**Closed by dlowder-salesforce** 2020-04-09 01:58 UTC
Labels: bug

**Comment by Erbsenfresser** [comment] 2020-10-22 15:32
> We had this same problem with react-navigation. Our solution was similar to the one you suggested @oscadev. When we navigate to a new screen, we render an empty View component for the screen underneath in the stack.

Hi, can you provide an example? I have the same problem and can't figure it out.
