### ISSUE TITLE
tvOS: onFocus issue

### ISSUE THREAD

**Issue by ishaqashraf** [react-native-community/react-native-tvos#55] opened 2020-03-16 19:19 UTC
is there any way that onFocus and onBlur works on `View` component on tvOS? 
i have a list inside my View component and i want to catch the onfocus and onblur when user focus on that View.
i added `hasTVPreferredFocus` prop on View but no luck 
here is my code sample : 
`<View hasTVPreferredFocus={true} onFocus={() => console.log('focus')} style={homeScreenStyles.sliderRowContainer}>
          {
                      sliderData.map((item, index) => {
                          return <Text>{item.title}}</Text>
                      })
                  }
        </View>`
react native : 0.59.9

**Comment by dlowder-salesforce** [comment] 2020-03-17 00:35
- I would recommend moving to the current supported version of react-native-tvos (0.61.5-0)
- `View` is not focusable, but `Touchable` and friends are, plus a few other components (e.g. `TextInput`)

**Comment by ishaqashraf** [comment] 2020-03-17 07:58
yes i used `Touchables`but in the above situation i need to onFocus and onBlur func on View. do you have any suggestion?

**Comment by ishaqashraf** [comment] 2020-03-17 08:00
like i have a swiper component and i want to disable auto scrolling when user focus on that View and then when unFocus the auto scrolling will enable

**Closed** 2020-03-19 14:49 UTC

**Comment by ajoykarmakar** [comment] 2021-06-24 08:48
The issue is still present.
